---
- hosts: all
  become: yes
  tasks:
    - name: sync repo and update packages (Ubuntu)
      apt:
        update_cache: yes
        upgrade: dist
      when: ansible_distribution == "Ubuntu"
    - name: sync repo and update packages (Rocky)
      dnf:
        update_cache: yes
        update_only: yes
      when: ansible_distribution == "Rocky"

- hosts: ubuntu_servers
  become: yes
  tasks:
    - name: install apache2
      apt:
        name: apache2
        state: latest
