---
- hosts: all
  become: yes
  tasks:

  - name: update repo
    ansible.builtin.apt:
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: upgrade packages
    ansible.builtin.apt:
      upgrade: yes
    when: ansible_distribution == "Ubuntu"

  - name: install apache2
    ansible.builtin.apt:
      name: apache2
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: update repo
    ansible.builtin.dnf:
      update_cache: yes
    when: ansible_distribution == "Rocky"

  - name: upgrade packages
    ansible.builtin.dnf:
      name: "*"
      state: latest
    when: ansible_distribution == "Rocky"

  - name: install apache2
    ansible.builtin.dnf:
      name: httpd
      state: latest
    when: ansible_distribution == "Rocky"
